### PR TITLE
ci: use reusable formatting workflow

### PR DESCRIPTION
**Pull request by thazhemadam**
Use organisation wide formatting workflow.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
How's this?

**Comment by thazhemadam** [comment]
There's still seems to be a few issues that I'm working out. But the general set up itself works.

**Comment by ChrisRackauckas** [comment]
`Format Check / Format Checks / Comment Formatting Suggestions on PR (pull_request) Skipped`

Is this one supposed to show up as not run?

**Comment by thazhemadam** [comment]
> `Format Check / Format Checks / Comment Formatting Suggestions on PR (pull_request) Skipped`
>
> Is this one supposed to show up as not run?

Yes. The "Comment Formatting Suggestions" step is run only if there are actually formatting suggestions that need to be commented. If the format checks are passing, then that job isn't run.

**Pull request merged**
