### PR TITLE
Use ArrayInterface.ismutable, further reduce allocations

### PR DESCRIPTION
**Pull request by chriselrod**
Follow up to https://github.com/SciML/ExponentialUtilities.jl/pull/55, now using `ArrayInterface.ismutable` and further reducing allocations by reusing buffers between `exp_pade_p` and `exp_pade_q`, and using inplace `lu!` and `rdiv!` instead of `/`.
Also manually power_by_squaring, which is really straightforward here because our power is a power of 2.

### CODE REVIEW

**Comment by chriselrod** [comment]
I'm still getting a ton of allocations for dual numbers. Let me try and find out why and possibly fix that.

**Comment by chriselrod** [comment]
Timings:
```julia
julia> using StaticArrays, ExponentialUtilities, DataFrames, ProgressMeter, ForwardDiff, LinearAlgebra

julia> function comptimes_smvm_dual(N)
           times = Array{Float64}(undef, 2, 2, N)
           @showprogress for n ∈ N:-1:1
               Am = Matrix{ForwardDiff.Dual{Nothing, Float64, 4}}(undef, n, n)
               Am .= rand.()
               nx = opnorm(Am, 1)
               @. Am = 10 / nx
               A = SMatrix{n,n}(Am)
               times[1,1,n] = @elapsed ExponentialUtilities.exp_generic(A)
               times[2,1,n] = @elapsed ExponentialUtilities.exp_generic(Am)
               times[1,2,n] = @belapsed ExponentialUtilities.exp_generic($A)
               times[2,2,n] = @belapsed ExponentialUtilities.exp_generic($Am)
           end
           times
       end
comptimes_smvm_dual (generic function with 1 method)

julia> times_smvm_dual = comptimes_smvm_dual(16);
Progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| Time: 0:07:58

julia> DataFrame(:smatrix_compile => times_smvm_dual[1,1,:], :matrix_compile => times_smvm_dual[2,1,:], :smatrix_bench => times_smvm_dual[1,2,:], :matrix_bench => times_smvm_dual[2,2,:])
16×4 DataFrame
 Row │ smatrix_compile  matrix_compile  smatrix_bench  matrix_bench
     │ Float64          Float64         Float64        Float64
─────┼──────────────────────────────────────────────────────────────
   1 │        0.168445     4.259e-6       9.35616e-8     4.68337e-7
   2 │        0.251845     7.282e-6       2.87313e-7     1.297e-6
   3 │        0.679288     7.835e-6       1.6746e-6      2.31133e-6
   4 │        1.11464      9.196e-6       1.5632e-6      2.38811e-6
   5 │        1.89315      1.1946e-5      3.51912e-6     4.70886e-6
   6 │        2.84844      2.586e-5       6.8312e-6      9.813e-6
   7 │        4.62803      2.5013e-5      1.099e-5       1.5294e-5
   8 │        6.89105      1.8151e-5      1.7448e-5      1.1548e-5
   9 │       10.4108       2.6296e-5      2.6981e-5      1.8736e-5
  10 │       15.2936       4.0077e-5      3.1583e-5      3.1688e-5
  11 │       22.8381       5.1005e-5      4.391e-5       4.3097e-5
  12 │       32.8263       4.0929e-5      5.9243e-5      3.2002e-5
  13 │       46.6762       5.6186e-5      7.9491e-5      4.6836e-5
  14 │       81.2257       8.3039e-5      0.000111912    7.2997e-5
  15 │       32.5716       0.000100136    0.00011846     9.4592e-5
  16 │       42.4744       7.7891e-5      0.000144024    7.1627e-5
```
Before this PR, roughly comparable benchmarks:
```julia
 Row │ smatrix_compile  matrix_compile  smatrix_bench  matrix_bench
     │ Float64          Float64         Float64        Float64
─────┼──────────────────────────────────────────────────────────────
   1 │        0.16524      8.709e-6       6.04059e-8    2.51556e-6
   2 │        0.39773      8.492e-6       2.77579e-7    1.4094e-6
   3 │        0.896326     1.2181e-5      1.5819e-6     3.28263e-6
   4 │        1.61668      3.3786e-5      1.4519e-6     9.52e-6
   5 │        2.70417      3.8427e-5      3.22213e-6    1.5197e-5
   6 │        4.18516      4.4343e-5      6.1734e-6     2.3291e-5
   7 │        6.27477      6.0731e-5      1.0529e-5     3.5902e-5
   8 │        9.0276       7.5351e-5      1.6427e-5     4.8992e-5
   9 │       13.3863       8.0787e-5      2.4501e-5     6.5425e-5
  10 │       19.6654       9.9914e-5      2.9916e-5     8.4538e-5
  11 │       28.2391       0.00012648     4.0521e-5     0.000111313
  12 │       38.8576       0.000162249    5.5076e-5     0.00014215
  13 │       53.7328       0.000206064    7.7038e-5     0.000182754
  14 │       86.1779       0.000244339    0.000102372   0.000223501
  15 │       39.6956       0.000280084    0.000109122   0.000269563
  16 │       48.1787       0.000358121    0.000135535   0.00034212
```
>2x better performance with `Matrix`.

**Review by YingboMa — APPROVED** [review]
This is amazing! Thanks!

**Comment by YingboMa** [comment]
Please merge if you feel comfortable with this PR.

**Comment by chriselrod** [comment]
I don't have commit/merge access.

**Comment by andreasnoack** [comment]
> From generic matmul

The one in `LinearAlgebra`?

**Comment by chriselrod** [comment]
> > From generic matmul
> 
> The one in `LinearAlgebra`?

Yes.
```julia
julia> using LinearAlgebra, ForwardDiff, ExponentialUtilities

julia> A = ForwardDiff.Dual{Nothing,Float64,4}.(rand(8,8));

julia> B = ForwardDiff.Dual{Nothing,Float64,4}.(rand(8,8));

julia> C = similar(A);

julia> @benchmark mul!($C,$A,$B)
BenchmarkTools.Trial:
  memory estimate:  224 bytes
  allocs estimate:  4
  --------------
  minimum time:     1.758 μs (0.00% GC)
  median time:      1.767 μs (0.00% GC)
  mean time:        1.773 μs (0.00% GC)
  maximum time:     3.896 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     10

julia> @benchmark LinearAlgebra.generic_matmatmul!($C,'N','N',$A,$B)
BenchmarkTools.Trial:
  memory estimate:  224 bytes
  allocs estimate:  4
  --------------
  minimum time:     1.758 μs (0.00% GC)
  median time:      1.767 μs (0.00% GC)
  mean time:        1.773 μs (0.00% GC)
  maximum time:     3.791 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     10

julia> @benchmark ExponentialUtilities.naivemul!($C,$A,$B)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     270.638 ns (0.00% GC)
  median time:      272.063 ns (0.00% GC)
  mean time:        272.304 ns (0.00% GC)
  maximum time:     321.771 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     315
```

**Pull request merged**
